added new version of zsh.install

diff --git a/instal/zsh.install b/instal/zsh.install
--- a/instal/zsh.install
+++ b/instal/zsh.install
@@ -1,27 +1,72 @@
 #!/usr/bin/env bash
 
+# color declaration.
 GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m' # No color
 
+# usage and exit function.
+usageAndExit(){
+    echo -e "Usage: $0"
+    #echo -e "Example: $0"
+    exit 1
+}
+
+# check if this script is running as root.
+# comment the following statement if not required
 if [ $UID -ne 0 ]; then
-    echo -e "${RED}$0 must be run as root${NC}"
+    echo -e "${RED}$0 must be run as root.${NC}"
+    usageAndExit
+fi
+
+# check if correct number of parameters are passed to this script.
+# change the following number: 1 == no parameters, 2 == 1 parameters ecc.
+#if [ "$#" -ne 1 ]; then
+#    echo -e "${RED}Parameters missing.${NC}"
+#    usageAndExit
+#fi
+
+# insert the required packages, space separated.
+# if no dependencies required for this script, just skip it without modify.
+dep_req=( git curl )
+# check if required packages are installed
+dep_not_found=( )
+i=0
+for dep in "${dep_req[@]}"
+do
+    q=$(dpkg-query -W -f='${Status}' ${dep} 2>/dev/null | grep -c "ok installed")
+    if [ ${q} -eq 0 ]; then
+        dep_not_found[$i]=${dep}
+        ((i++))
+    fi
+done
+if [ ${i} -ne 0 ]; then
+    echo -e "${RED}Abort: Dependency package/s not found: ${NC}"
+    printf '%s ' "${dep_not_found[@]}"
+    echo ""
     exit 1
 fi
 
-echo -e "${GREEN}=== INSTALL ZSH...${NC}"
-apt-get install zsh curl git
+# script logic start here
+USER=andrea
 
-echo "=== Changing shell for andrea..."
-chsh -s /bin/zsh andrea
+echo -e "${GREEN}=== INSTALL ZSH...${NC}"
+apt-get install zsh
+
+echo "=== Changing shell for user $USER..."
+chsh -s /bin/zsh $USER
 echo "=== shell changed!"
 
 echo -e "${GREEN}=== INSTALLING oh-my-zsh...${NC}"
-su - andrea -c "curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh"
+su - $USER -c "curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh"
 echo "=== oh-my-zsh installed!"
 cp ../zsh/.zshrc ~
-echo "=== .zshrc copied into ~"
 cp ../zsh/my.zsh-theme ~/.oh-my-zsh/themes
-echo "=== my.zsh-theme copied into ~/.oh-my-zsh/themes"
 
+git clone https://github.com/zsh-users/zsh-syntax-highlighting.git 
+mv zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/
+
+chown -R $USER:$USER ~/.zshrc
+chown -R $USER:$USER ~/.oh-my-zsh
 echo -e "${GREEN}=== FINISH! (reboot needed)${NC}"
+
